### PR TITLE
add travis ( and repair gradle test)

### PR DESCRIPTION
**Pull request by sakamotodesu**

### CODE REVIEW

**Comment by kevinrobayna** [comment]
oh yes i was thinking about this too great!

**Comment by rodionmoiseev** [comment]
Excellent, thanks! Will merge soon. 

So the tests did not pass without the findbugs dep? I wonder what was the exact problem.

**Comment by rodionmoiseev** [comment]
Oh I see. You get a compilation error, about an unaccessible `@Nullable` annotation class. Actually, I should probably remove `@Nullable` annotation, as I am not really using it.

```
:tools:compileTestJava
/home/rodion/work/projects/tools/c10n/tools/src/test/java/com/github/rodionmoiseev/c10n/tools/inspector/AbstractC10NInspectorTest.java:34: エラー: シンボルを見つけられません
import javax.annotation.Nullable;
                       ^
  シンボル:   クラス Nullable
  場所: パッケージ javax.annotation
/home/rodion/work/projects/tools/c10n/tools/src/test/java/com/github/rodionmoiseev/c10n/tools/inspector/AbstractC10NInspectorTest.java:92: エラー: シンボルを見つけられません
            public Locale apply(@Nullable Translation input) {
                                 ^
  シンボル: クラス Nullable
注意:/home/rodion/work/projects/tools/c10n/tools/src/test/java/com/github/rodionmoiseev/c10n/tools/search/C10NInterfaceSearchTest.javaの操作は、未チェックまたは安全ではありません。
注意:詳細は、-Xlint:uncheckedオプションを指定して再コンパイルしてください。
エラー2個
:tools:compileTestJava FAILED
```

**Comment by sakamotodesu** [comment]
> Oh I see. You get a compilation error

Yes.
I should have described the reason, sorry.

**Comment by rodionmoiseev** [comment]
The build is failing. I will investigate to why later :(

**Comment by sakamotodesu** [comment]
Oh sorry, too.
I forgot to change the gradle version on PR.

* Error (execute on windows)

> failed to read class file C:\idea\c10n\core\build\classes\test\com\github\rodionmoiseev\c10n\AnnotationBindingConfigurationErrorTest$1.class

If you are changing the version of gradle to 2.8, this error is repaired.

**Comment by rodionmoiseev** [comment]
It worked! Excellent, thanks!

**Pull request merged**
